
name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: ESLint Check
        run: npm run lint
      - name: Test Check
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build project
        run: npm build
